### ISSUE TITLE
trying to run model from example.

### ISSUE THREAD

**Issue by syntrop** [regel/loudml#13]
I'm trying to run my first model, by following the docs (http://loudml.io/guide/en/loudml/reference/current/cli-create-model.html)

My JSON file looks almost exactly the same as in the example. I just change DB and table names.

DB source: influx
server: localhost

and I'm getting strange errors:

`loudml create-model model.json`

ERROR:
```
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.2', 'console_scripts', 'loudml')()
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 417, in main
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 120, in exec
  File "/usr/lib/python3.5/dist-packages/loudml/filestorage.py", line 53, in create_model
  File "/usr/lib/python3.5/dist-packages/loudml/filestorage.py", line 39, in _write_model
PermissionError: [Errno 13] Permission denied: '/var/lib/loudml/models/avg_temp2-model.lmm'
```

I've check permissions. I even added g+w for the /var/lib/loudml/models

in my case temperature field is float

**Comment by regel** [comment]
The /var/lib/loudml directory should be owned by the loudml user. This is a system user, without privileges, that was created at package installation.

The command below should solve the issue:

chmod -R loudml: /var/lib/loudml

Then restart the daemon.

Best,

Sébastien

**Comment by syntrop** [comment]
Hi Sébastien

Thank you for the reply. I think you wanted to write **chown**

I my case I have a correct owner:
```
dmitry@saga:/var/lib$ ls -l

drwxr-xr-x 3 loudml   nogroup  4096 Mar  9 16:09 loudml
```

```
dmitry@saga:/var/lib/loudml$ ls -la
total 12
drwxr-xr-x  3 loudml nogroup 4096 Mar  9 16:09 .
drwxr-xr-x 31 root   root    4096 Mar 13 14:43 ..
drwxrwxr-x  2 loudml nogroup 4096 Mar  9 16:09 models

```


but still getting:
```
loudml create-model model.json
/usr/lib/python3/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "/usr/bin/loudml", line 11, in <module>
    load_entry_point('loudml==1.2', 'console_scripts', 'loudml')()
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 417, in main
  File "/usr/lib/python3.5/dist-packages/loudml/cli.py", line 120, in exec
  File "/usr/lib/python3.5/dist-packages/loudml/filestorage.py", line 53, in create_model
  File "/usr/lib/python3.5/dist-packages/loudml/filestorage.py", line 39, in _write_model
PermissionError: [Errno 13] Permission denied: '/var/lib/loudml/models/avg_temp2-model.lmm'

```

**Comment by syntrop** [comment]
solved by installing version 1.2.2 and executing this as root

**Comment by regel** [comment]
Thank you @syntrop - Your can actually add your local user in the group 'loudml' and it will allow you to use the CLI as local user.

This is an important point, and we have to fix the documentation.

Thanks for catching this!

**Comment by regel** [comment]
I'm reopening. Adding the local user to 'loudml' group is not sufficient.
usermod -a -G loudml regel

Version 1.2.3 creates the .lmm files with 644 permissions, but we should use 664 instead.

A quick workaround is:
chmod 664 /var/lib/loudml/models/*.lmm

**Comment by regel** [comment]
Workaround documented in previous release. Also, a specific note for this has been added in the documentation. I believe file permissions are ok now with Debian and EL7 release.
